pepfile: config/pep/config.yaml

# If testing set true
testing: False

project-name: "pilot2"

data-handling:
  # path to store data within the workflow
  data: "data/"
  resources: "resources/"

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter_seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"

human-filtering:
  use-local: True
  # path to a locally stored human reference genome
  local-path: "/groups/ds/databases_refGenomes/refGenomes/latest/human/GCA_000001405.29_GRCh38.p14_genomic.fna.gz"
  # if use-local = False the reference genome is downloaded via the following link
  download-path: "https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz"


# if host filtering is wanted
host_filtering:
  do_host_filtering: False
  host_name: "" #"pig"
  ref_genome: "" #"resources/ref_genome/GCF_000003025.6_Sscrofa11.1_genomic.fa.gz"

kraken:
  download-path: "https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_20230605.tar.gz"
  db-name: "k2_pluspf"
  # species/kingdom to separate with taxIDs in same order
  taxIDs-ref: {
      bacteria: 2,
      fungi: 4751,
      archaea: 2157,
      viruses: 10239,
    }

checkm2: "CheckM2_database/uniref100.KO.1.dmnd"
kaiju:
  download: "https://kaiju-idx.s3.eu-central-1.amazonaws.com/2023/kaiju_db_refseq_nr_2023-06-17.tgz"
  fmi-file: "kaiju_db/kaiju_db_refseq_nr.fmi"

binning:
  # threshold for the minimum contig length to be accepted by metabinner and vamb
  min_contig_length: 300
  # some metabinner parameter
  kmer_length: 3
  threads: 24

rosella:
  gitURL: "https://github.com/rhysnewell/rosella.git"

das_tool:
  # cores to use for das_tool
  threads: 64
  # available binners are: metabinner, metabat, metabat2, metacoag, concoct, rosella, vamb
  binner-list: ["metabat","metacoag"]

MAG-criteria:
  min-completeness: 50.00
  max-contamination: 30.00

card:
  dbfile: "card.json"
  url: "https://card.mcmaster.ca/latest/data"

gtdb:
  use_local: True
  dbfolder: "/local/work/josefa/ResMAG/resources/gtdb/release220/"

## string term used for formatting output tables
tablular-config: '/>github<\/a>/a \\t\t\t</li>\n\t\t\t<li class="nav-item"> \n\t\t\t\t<a class="nav-link" href="#">'