pepfile: config/pep/config.yaml

# If testing set true
testing: False

project-name: "strawpigs"

data-handling:
  # path to store data within the workflow
  data: "data/"
  resources: "resources/"

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter_seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"

kraken:
  kraken-db: "/projects/pig-muenster/resmag/resources/krakenDB/strawpigs/"
  # species/kingdom to separate with taxIDs in same order
  # ref: ['bacteria','fungi', 'pig', 'human', 'plant']
  ref-analysis: ["bacteria", "fungi"]
  taxIDs-ref: { bacteria: 2, fungi: 4751, pig: 9823, human: 9606, plant: 33090 }

binning:
  # threshold for the minimum contig length to be accepted by metabinner and vamb
  min_contig_length: 300
  # some metabinner parameter
  kmer_length: 3
  threads: 24

rosella:
  gitURL: "https://github.com/rhysnewell/rosella.git"

das_tool:
  # cores to use for das_tool
  threads: 32
  binner-list: ["metabinner", "metabat2", "metacoag", "rosella", "vamb"]
