pepfile: config/pep/config.yaml

project-name: 'strawpigs'

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter_seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"

reference-genomes:
  # list of reference names
  reference-species: ["pig"] #, "human"]
  # file extension of the reference genome,
  # can be .fa, .fasta, .fna, optionally .gz
  reference-file-ext: ".fna.gz"
  # directory of reference genomes, e.g resources/reference/
  reference-dir: resources/reference/
