pepfile: config/pep/config.yaml


quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter_seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"