pepfile: config/pep/config.yaml

## Please change to a name describing your project
## All results can be found under results/project-name/
project-name: "test"
#
run-date: "2025-01-06"

data-handling:
  # path to store data within the workflow
  data: data/
  # path where databases and reference genomes are stored
  resources: resources/

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter-seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"

# reads are always filtered for human contamination
human-filtering:
  # if you have a human reference genome on your device,
  # you can set use-local to True and specify the path to the human reference genome
  use-local: True
  # path to a locally stored human reference genome
  local-path: /groups/ds/databases_refGenomes/refGenomes/latest/human/GCA_000001405.29_GRCh38.p14_genomic.fna.gz
  # if use-local = False the reference genome is downloaded via the following url
  download-path: https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz

# if filtering for non-human host is required,
# specify a host name and the path to the reference genome
host-filtering:
  do-host-filtering: False
  #e.g.: pig
  host-name: 
  #e.g.: resources/ref_genome/GCF_000003025.6_Sscrofa11.1_genomic.fa.gz
  ref-genome: 

# minimum contig length used during assembly step
min-contig-length: 300

das-tool:
  # cores to use for das_tool
  threads: 64
  binner-list: ["metabat","metacoag"]

MAG-criteria:
  min-completeness: 50.00
  max-contamination: 30.00

### Handling of different databases
kaiju:
  download: https://kaiju-idx.s3.eu-central-1.amazonaws.com/2023/kaiju_db_refseq_nr_2023-06-17.tgz
  fmi-file: kaiju_db/kaiju_db_refseq_nr.fmi

checkm2: CheckM2_database/uniref100.KO.1.dmnd

## The GTDB has about 100 Gb
## if use-local is set to False this will be downloaded during the pipeline run
gtdb:
  use-local: True
  # if use-local is set to True, please specify the folder where the decompressed database is stored
  # this path is expected to lay under the data-handling resources folder
  db-folder: gtdb/release220/

card:
  version: v3.3.0
  dbfile: card.json
  url: https://card.mcmaster.ca/latest/data

## string term used for formatting output tables
tablular-config: '/>github<\/a>/a \\t\t\t</li>\n\t\t\t<li class="nav-item"> \n\t\t\t\t<a class="nav-link" href="#">'

# If testing set true
testing: False