pepfile: config/pep/config.yaml
pathogens: config/pathogens.csv

# If testing set true
testing: False

project-name: "lanuv"

data-handling:
  # path to store data within the workflow
  data: "data/"
  resources: "resources/"

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter_seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"

pathogen-recruitment:
  use-local: True
  # path to lacally stored pathogen genomes
  local-path: "/groups/ds/databases_refGenomes/refGenomes/latest/pathogen/"
  # if use-local = False the reference genome is downloaded via the following link
  download-path: "https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/{accession}/download?include_annotation_type=GENOME_FASTA"


# human-filtering:
#   use-local: True
#   # path to a locally stored human reference genome
#   local-path: "/groups/ds/databases_refGenomes/refGenomes/latest/human/GCA_000001405.29_GRCh38.p14_genomic.fna.gz"
#   # if use-local = False the reference genome is downloaded via the following link
#   download-path: "https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz"


# # if host filtering is wanted
# host_filtering:
#   do_host_filtering: False
#   host_name: "" #"pig"
#   ref_genome: "" #"resources/ref_genome/GCF_000003025.6_Sscrofa11.1_genomic.fa.gz"

checkm2: "CheckM2_database/uniref100.KO.1.dmnd"

binning:
  # threshold for the minimum contig length to be accepted by metabinner and vamb
  min_contig_length: 300
  # some metabinner parameter
  kmer_length: 3
  threads: 24

minimap2:
  # cores to use for mapping
  threads: 64

MAG-criteria:
  min-completeness: 85.00
  max-contamination: 5.00

## string term used for formatting output tables
tablular-config: '/>github<\/a>/a \\t\t\t</li>\n\t\t\t<li class="nav-item"> \n\t\t\t\t<a class="nav-link" href="#">'